### ISSUE TITLE
Why does this error happen？ Is it wrong with the size of frames? ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by dayekuaipao** [justayak/cabbage#4]
Traceback (most recent call last):
  File "my_run.py", line 14, in <module>
    execute_multiple_people_tracking(video_loc, X, Dt, video_name, dmax, settings_loc)  
  File "/home/shaun/cabbage/cabbage/MultiplePeopleTracking.py", line 57, in execute_multiple_people_tracking
    gg.build(Dt, X, W, batch_size=batch_size)
  File "/home/shaun/cabbage/cabbage/MultiplePeopleTracking.py", line 95, in build
    lookup = AABBLookup(Dt, X)
  File "/home/shaun/cabbage/cabbage/features/combined.py", line 40, in __init__
    im = get_element(X[frame-1], (x,y,w,h), (W, H), True)
  File "/home/shaun/cabbage/cabbage/features/ReId.py", line 23, in get_element
    I = resize(I, shape, mode='constant').copy()
  File "/home/shaun/anaconda3/envs/tensorflow/lib/python3.6/site-packages/skimage/transform/_warps.py", line 135, in resize
    preserve_range=preserve_range)
  File "/home/shaun/anaconda3/envs/tensorflow/lib/python3.6/site-packages/skimage/transform/_warps.py", line 819, in warp
    _clip_warp_output(image, warped, order, mode, cval, clip)
  File "/home/shaun/anaconda3/envs/tensorflow/lib/python3.6/site-packages/skimage/transform/_warps.py", line 570, in _clip_warp_output
    min_val = input_image.min()
  File "/home/shaun/anaconda3/envs/tensorflow/lib/python3.6/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by jutanke** [comment]
Hi, could it be that the bounding box of your human candidate detection is outside the visible frame? The code is quite brittle (as it was a uni lab) so it might be that you need to manually filter out bb's that are not completely in the frame

**Comment by dayekuaipao** [comment]
Thank for your kindness,I will check it.

**Comment by dayekuaipao** [comment]
That`s It.Thank you.

**Comment by gyc521zsc** [comment]
I also meeted this issue.Coule you tell me what did you do.
Here are my code
video_name = 'video'
X = np.zeros((110, 1920, 1980, 3))  # the whole video loaded as np array
dmax = 100
Dt = np.zeros((110, 6))  # m=number of detections

Thank you very much for replying to my message.
