### ISSUE TITLE
Import error for cabbage

### ISSUE THREAD

**Issue by akhilkumarco007** [justayak/cabbage#8]
I am facing issues to import cabbage. It still shows up in pip but I don't know why I cant import it. Can you please help solve it.

**Comment by AIPlusPlus** [comment]
Adding \_\_init\_\_.py in cabbage package resolved this issue for me

**Comment by kingwmk** [comment]
i got a importerror:
Traceback (most recent call last):
File "test.py", line 2, in 
from cabbage.MultiplePeopleTracking import execute_multiple_people_tracking
File "/home/wangmingkun/code/cabbage/cabbage/MultiplePeopleTracking.py", line 5, in 
from cabbage.features.GenerateFeatureVector import pairwise_features
File "/home/wangmingkun/code/cabbage/cabbage/features/GenerateFeatureVector.py", line 4, in 
from cabbage.features.deepmatching import DeepMatching
File "/home/wangmingkun/code/cabbage/cabbage/features/deepmatching.py", line 6, in 
from pppr import aabb
ImportError: No module named 'pppr'

How can I solve it?  excuse me,@knezevicmarko88

**Comment by smidm** [comment]
You haven't successfully run `install.sh`, see https://github.com/jutanke/cabbage/blob/master/install.sh.
